FROM postgres:13

# To populate the table at image creation time.
# COPY Tables/minimalExample.pgsql /
# RUN { POSTGRES_USER=desyl POSTGRES_PASSWORD=123 /usr/local/bin/docker-entrypoint.sh postgres & }; sleep 60; pg_restore --create -h localhost -U desyl -d postgres  -p 5432 /minimalExample.pgsql -v && rm /minimalExample.pgsql

